### ISSUE TITLE
supabase配置失败,恳请作者给出详细一丝丝的supabase配置教程(supabase configuration failure, I implore the author to give a detailed hint of supabase configuration tutorials)

### ISSUE THREAD

**Issue by sanbei011** [LevinIgor/vue-supabase-chat#5]
你好,我是一名来自中国的学生,在部署您的项目时,遇到了supabase配置的问题,经过我的研究无果,特向您请教

> Hello, I am a student from China, in the deployment of your project, encountered a supabase configuration problems, after my research to no avail, especially to ask you for advice!

![image](https://github.com/LevinIgor/vue-supabase-chat/assets/95988545/c208161d-b865-4ca2-9c0e-22d70b9df30c)
这张图片中显示创建supabase数据库需要五列,但是经过我实际的测试,还有第六列:"location",下面是报错信息:

> (This picture shows that five columns are needed to create a supabase database, but after my actual test, there is a sixth column: "location", the following is the error message.)

`{
    "code": "PGRST204",
    "details": null,
    "hint": null,
    "message": "Column 'location' of relation 'message' does not exist"
}`

而且,按照作者给出的supabase配置,还有**header**处的几个**状态**无法正常获取并显示

> Also, according to the supabase configuration given by the author, there are a couple of **states** at the **header** that are not fetched and displayed properly

![image](https://github.com/LevinIgor/vue-supabase-chat/assets/95988545/b650c8d3-1e2d-42c0-9c3b-d8837a30dd91)
如果作者能给出正确的做法,我将感激不尽!!

> I would be grateful if the author could give me the correct way to do this!!!!

**Comment by LevinIgor** [comment]
The new instructions are ready, you can use them

https://github.com/LevinIgor/vue-supabase-chat/blob/main/README.md

**Comment by sanbei011** [comment]
thanks

**Comment by sanbei101** [comment]
> The new instructions are ready, you can use them
> 
> https://github.com/LevinIgor/vue-supabase-chat/blob/main/README.md

thanks！
